-- SOLUSI GENZ V6 — ACTIVATE ALL CORE FEATURES
-- Jalankan SEKALI di Supabase SQL Editor setelah commit ZIP V6.
-- Aman untuk struktur website saat ini: order, status, bukti TF, akses akun,
-- affiliate, komisi, pencairan, admin, dan foto produk.

begin;

create extension if not exists pgcrypto;

create or replace function public.sg_is_admin()
returns boolean language sql stable security definer set search_path=public
as $$ select lower(coalesce(auth.jwt()->>'email',''))='paninengan482@gmail.com' $$;

-- Pastikan kolom order inti tersedia.
alter table public.sg_orders add column if not exists payment_proof_data_url text;
alter table public.sg_orders add column if not exists access_text text;
alter table public.sg_orders add column if not exists access_note text;
alter table public.sg_orders add column if not exists access_delivered_at timestamptz;

-- Pastikan foto produk editable.
alter table public.sg_catalog_products add column if not exists image_data_url text;

-- Affiliate V6 sengaja memakai tabel terpisah supaya tidak bentrok dengan percobaan schema lama.
create table if not exists public.sg_affiliates_v6(
  email text primary key,
  user_id uuid,
  referral_code text unique not null,
  active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sg_referrals_v6(
  buyer_email text primary key,
  buyer_user_id uuid,
  affiliate_email text not null,
  referral_code text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.sg_commissions_v6(
  id uuid primary key default gen_random_uuid(),
  invoice text unique not null,
  affiliate_email text not null,
  buyer_email text not null,
  order_amount bigint not null default 0,
  commission_amount bigint not null default 0,
  status text not null default 'tersedia',
  created_at timestamptz not null default now()
);

create table if not exists public.sg_withdrawals_v6(
  id bigint generated by default as identity primary key,
  affiliate_email text not null,
  amount bigint not null,
  method text not null,
  account_name text not null,
  account_number text not null,
  status text not null default 'Diproses',
  admin_note text,
  proof_data_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.sg_store_settings_ext add column if not exists withdraw_minimum bigint default 10000;
update public.sg_store_settings_ext set withdraw_minimum=coalesce(withdraw_minimum,10000) where id=1;

-- Sinkronkan akun affiliate. Kode stabil berdasarkan email.
create or replace function public.sg_affiliate_sync_self_v6()
returns jsonb language plpgsql security definer set search_path=public as $$
declare e text:=lower(coalesce(auth.jwt()->>'email','')); u uuid:=auth.uid(); c text; paid_count bigint;
begin
  if e='' then raise exception 'Harus login'; end if;
  c:='SG'||upper(substr(md5(e),1,8));
  select count(*) into paid_count from public.sg_orders o
    where lower(o.email)=e and o.status in ('Lunas','Dibayar','Diproses','Selesai');
  insert into public.sg_affiliates_v6(email,user_id,referral_code,active,updated_at)
  values(e,u,c,paid_count>0,now())
  on conflict(email) do update set user_id=coalesce(excluded.user_id,sg_affiliates_v6.user_id),
    active=(sg_affiliates_v6.active or excluded.active),updated_at=now();
  return jsonb_build_object('email',e,'referral_code',c,'eligible',paid_count>0);
end $$;

create or replace function public.sg_affiliate_attach_referral_v6(p_referral_code text)
returns boolean language plpgsql security definer set search_path=public as $$
declare buyer text:=lower(coalesce(auth.jwt()->>'email','')); uid uuid:=auth.uid(); owner_email text; code text:=upper(trim(coalesce(p_referral_code,'')));
begin
  if buyer='' then raise exception 'Harus login'; end if;
  if code='' then return false; end if;
  select email into owner_email from public.sg_affiliates_v6 where referral_code=code and active=true limit 1;
  if owner_email is null or owner_email=buyer then return false; end if;
  insert into public.sg_referrals_v6(buyer_email,buyer_user_id,affiliate_email,referral_code)
  values(buyer,uid,owner_email,code)
  on conflict(buyer_email) do nothing;
  return true;
end $$;

-- Buat order: email selalu mengikuti akun login, jadi status bisa dibaca kembali dengan aman.
create or replace function public.sg_create_order_v6(
  p_invoice text,p_product_name text,p_price bigint,p_customer_name text,
  p_whatsapp text,p_payment_method text
) returns jsonb language plpgsql security definer set search_path=public as $$
declare e text:=lower(coalesce(auth.jwt()->>'email',''));
begin
  if e='' then raise exception 'Harus login'; end if;
  if trim(coalesce(p_invoice,''))='' then raise exception 'Invoice tidak valid'; end if;
  if trim(coalesce(p_product_name,''))='' then raise exception 'Produk tidak valid'; end if;
  insert into public.sg_orders(invoice,product_name,price,customer_name,email,whatsapp,payment_method,status)
  values(upper(trim(p_invoice)),trim(p_product_name),greatest(0,coalesce(p_price,0)),
         coalesce(nullif(trim(p_customer_name),''),split_part(e,'@',1)),e,trim(coalesce(p_whatsapp,'')),
         coalesce(nullif(trim(p_payment_method),''),'Transfer Bank Mandiri'),'Menunggu Pembayaran');
  return jsonb_build_object('ok',true,'invoice',upper(trim(p_invoice)));
exception when unique_violation then
  raise exception 'Invoice sudah ada, coba lagi';
end $$;

-- Cek order dalam JSON supaya tidak gagal karena perbedaan tipe schema lama.
create or replace function public.sg_check_order_v6(p_invoice text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare e text:=lower(coalesce(auth.jwt()->>'email','')); j jsonb;
begin
  if e='' then raise exception 'Harus login'; end if;
  select jsonb_build_object(
    'invoice',o.invoice,'product_name',o.product_name,'price',o.price,'customer_name',o.customer_name,
    'email',o.email,'whatsapp',o.whatsapp,'payment_method',o.payment_method,'status',o.status,
    'created_at',o.created_at,'payment_proof_data_url',o.payment_proof_data_url,
    'access_text',o.access_text,'access_note',o.access_note,'access_delivered_at',o.access_delivered_at
  ) into j from public.sg_orders o
  where upper(o.invoice)=upper(trim(p_invoice)) and lower(o.email)=e limit 1;
  return j;
end $$;

create or replace function public.sg_submit_payment_v6(p_invoice text,p_proof_data_url text)
returns boolean language plpgsql security definer set search_path=public as $$
declare e text:=lower(coalesce(auth.jwt()->>'email',''));
begin
  if e='' then raise exception 'Harus login'; end if;
  if p_proof_data_url is null or length(p_proof_data_url)<30 then raise exception 'Bukti transfer wajib'; end if;
  update public.sg_orders set payment_proof_data_url=p_proof_data_url,status='Menunggu Verifikasi'
  where upper(invoice)=upper(trim(p_invoice)) and lower(email)=e
    and coalesce(status,'') not in ('Lunas','Dibayar','Diproses','Selesai','Dibatalkan');
  return found;
end $$;

-- Admin order list JSON.
create or replace function public.sg_admin_list_orders_v6()
returns jsonb language plpgsql security definer set search_path=public as $$
declare j jsonb;
begin
  if not public.sg_is_admin() then raise exception 'Akses admin ditolak'; end if;
  select coalesce(jsonb_agg(jsonb_build_object(
    'invoice',o.invoice,'customer_name',o.customer_name,'email',o.email,'whatsapp',o.whatsapp,
    'product_name',o.product_name,'price',o.price,'payment_method',o.payment_method,'status',o.status,
    'created_at',o.created_at,'payment_proof_data_url',o.payment_proof_data_url,
    'access_text',o.access_text,'access_note',o.access_note,'access_delivered_at',o.access_delivered_at
  ) order by o.created_at desc),'[]'::jsonb) into j from public.sg_orders o;
  return j;
end $$;

-- Set status + aktifkan affiliate pembeli + catat komisi inviter ketika pembayaran valid.
create or replace function public.sg_admin_set_status_v6(p_invoice text,p_status text)
returns boolean language plpgsql security definer set search_path=public as $$
declare o public.sg_orders%rowtype; comm bigint:=0; inviter text;
begin
  if not public.sg_is_admin() then raise exception 'Akses admin ditolak'; end if;
  if p_status not in ('Menunggu Pembayaran','Menunggu Verifikasi','Lunas','Dibayar','Diproses','Selesai','Dibatalkan') then
    raise exception 'Status tidak valid';
  end if;
  update public.sg_orders set status=p_status where upper(invoice)=upper(trim(p_invoice)) returning * into o;
  if not found then return false; end if;
  if p_status in ('Lunas','Dibayar','Diproses','Selesai') then
    -- Pembeli otomatis memperoleh affiliate aktif setelah transaksi valid.
    insert into public.sg_affiliates_v6(email,user_id,referral_code,active,updated_at)
    values(lower(o.email),null,'SG'||upper(substr(md5(lower(o.email)),1,8)),true,now())
    on conflict(email) do update set active=true,updated_at=now();

    select r.affiliate_email into inviter from public.sg_referrals_v6 r where r.buyer_email=lower(o.email) limit 1;
    if inviter is not null then
      select coalesce(round(p.commission_amount)::bigint,0) into comm
      from public.sg_catalog_products p where lower(p.name)=lower(o.product_name) order by p.created_at desc limit 1;
      comm:=coalesce(comm,0);
      if comm>0 then
        insert into public.sg_commissions_v6(invoice,affiliate_email,buyer_email,order_amount,commission_amount,status)
        values(o.invoice,inviter,lower(o.email),coalesce(o.price,0),comm,'tersedia')
        on conflict(invoice) do nothing;
      end if;
    end if;
  end if;
  return true;
end $$;

create or replace function public.sg_admin_deliver_access_v6(p_invoice text,p_access_text text,p_access_note text,p_status text)
returns boolean language plpgsql security definer set search_path=public as $$
begin
  if not public.sg_is_admin() then raise exception 'Akses admin ditolak'; end if;
  update public.sg_orders set
    access_text=nullif(trim(p_access_text),''),access_note=nullif(trim(p_access_note),''),
    access_delivered_at=case when nullif(trim(p_access_text),'') is not null then now() else access_delivered_at end,
    status=case when p_status in ('Diproses','Selesai') then p_status else status end
  where upper(invoice)=upper(trim(p_invoice));
  return found;
end $$;

-- Affiliate eligibility + summary.
create or replace function public.sg_affiliate_eligibility_v6()
returns jsonb language plpgsql security definer set search_path=public as $$
declare e text:=lower(coalesce(auth.jwt()->>'email','')); n bigint; c text;
begin
  if e='' then raise exception 'Harus login'; end if;
  select count(*) into n from public.sg_orders where lower(email)=e and status in ('Lunas','Dibayar','Diproses','Selesai');
  if n>0 then perform public.sg_affiliate_sync_self_v6(); end if;
  select referral_code into c from public.sg_affiliates_v6 where email=e limit 1;
  return jsonb_build_object('eligible',n>0,'referral_code',c);
end $$;

create or replace function public.sg_affiliate_me_v6()
returns jsonb language plpgsql security definer set search_path=public as $$
declare e text:=lower(coalesce(auth.jwt()->>'email','')); c text; refs bigint:=0; trx bigint:=0; total bigint:=0; paid bigint:=0; pending bigint:=0; avail bigint:=0;
begin
  if e='' then raise exception 'Harus login'; end if;
  perform public.sg_affiliate_sync_self_v6();
  select referral_code into c from public.sg_affiliates_v6 where email=e;
  select count(*) into refs from public.sg_referrals_v6 where affiliate_email=e;
  select count(*) into trx from public.sg_commissions_v6 where affiliate_email=e;
  select coalesce(sum(commission_amount),0) into total from public.sg_commissions_v6 where affiliate_email=e;
  select coalesce(sum(amount),0) into paid from public.sg_withdrawals_v6 where affiliate_email=e and status='Dibayar';
  select coalesce(sum(amount),0) into pending from public.sg_withdrawals_v6 where affiliate_email=e and status='Diproses';
  avail:=greatest(total-paid-pending,0);
  return jsonb_build_object('referral_code',c,'total_referrals',refs,'total_transactions',trx,
    'total_commission',total,'paid_commission',paid,'pending_withdrawal',pending,'available_balance',avail);
end $$;

create or replace function public.sg_affiliate_commissions_v6()
returns jsonb language plpgsql security definer set search_path=public as $$
declare e text:=lower(coalesce(auth.jwt()->>'email','')); j jsonb;
begin
  if e='' then raise exception 'Harus login'; end if;
  select coalesce(jsonb_agg(jsonb_build_object('invoice',c.invoice,'buyer_email',c.buyer_email,
    'order_amount',c.order_amount,'commission_amount',c.commission_amount,'status',c.status,'created_at',c.created_at)
    order by c.created_at desc),'[]'::jsonb) into j
  from public.sg_commissions_v6 c where c.affiliate_email=e;
  return j;
end $$;

create or replace function public.sg_request_withdraw_v6(p_amount bigint,p_method text,p_account_name text,p_account_number text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare e text:=lower(coalesce(auth.jwt()->>'email','')); total bigint:=0; paid bigint:=0; pending bigint:=0; avail bigint:=0; mn bigint:=10000; new_id bigint;
begin
  if e='' then raise exception 'Harus login'; end if;
  select coalesce(withdraw_minimum,10000) into mn from public.sg_store_settings_ext where id=1;
  select coalesce(sum(commission_amount),0) into total from public.sg_commissions_v6 where affiliate_email=e;
  select coalesce(sum(amount),0) into paid from public.sg_withdrawals_v6 where affiliate_email=e and status='Dibayar';
  select coalesce(sum(amount),0) into pending from public.sg_withdrawals_v6 where affiliate_email=e and status='Diproses';
  avail:=greatest(total-paid-pending,0);
  if coalesce(p_amount,0)<mn then raise exception 'Minimum pencairan Rp %',mn; end if;
  if p_amount>avail then raise exception 'Saldo tersedia tidak cukup'; end if;
  if trim(coalesce(p_account_name,''))='' or trim(coalesce(p_account_number,''))='' then raise exception 'Data rekening wajib lengkap'; end if;
  insert into public.sg_withdrawals_v6(affiliate_email,amount,method,account_name,account_number)
  values(e,p_amount,trim(p_method),trim(p_account_name),trim(p_account_number)) returning id into new_id;
  return jsonb_build_object('ok',true,'id',new_id);
end $$;

create or replace function public.sg_my_withdrawals_v6()
returns jsonb language plpgsql security definer set search_path=public as $$
declare e text:=lower(coalesce(auth.jwt()->>'email','')); j jsonb;
begin
 if e='' then raise exception 'Harus login'; end if;
 select coalesce(jsonb_agg(jsonb_build_object('id',w.id,'amount',w.amount,'method',w.method,'account_name',w.account_name,
   'account_number',w.account_number,'status',w.status,'admin_note',w.admin_note,'proof_data_url',w.proof_data_url,'created_at',w.created_at)
   order by w.created_at desc),'[]'::jsonb) into j from public.sg_withdrawals_v6 w where w.affiliate_email=e;
 return j;
end $$;

create or replace function public.sg_admin_list_withdrawals_v6()
returns jsonb language plpgsql security definer set search_path=public as $$
declare j jsonb;
begin
 if not public.sg_is_admin() then raise exception 'Akses admin ditolak'; end if;
 select coalesce(jsonb_agg(jsonb_build_object('id',w.id,'affiliate_email',w.affiliate_email,'amount',w.amount,'method',w.method,
   'account_name',w.account_name,'account_number',w.account_number,'status',w.status,'admin_note',w.admin_note,
   'proof_data_url',w.proof_data_url,'created_at',w.created_at) order by w.created_at desc),'[]'::jsonb)
 into j from public.sg_withdrawals_v6 w;
 return j;
end $$;

create or replace function public.sg_admin_finish_withdraw_v6(p_id bigint,p_paid boolean,p_note text,p_proof_data_url text)
returns boolean language plpgsql security definer set search_path=public as $$
begin
 if not public.sg_is_admin() then raise exception 'Akses admin ditolak'; end if;
 update public.sg_withdrawals_v6 set status=case when p_paid then 'Dibayar' else 'Ditolak' end,
   admin_note=nullif(trim(p_note),''),proof_data_url=nullif(trim(p_proof_data_url),''),updated_at=now()
 where id=p_id and status='Diproses';
 return found;
end $$;

create or replace function public.sg_admin_affiliate_summary_v6()
returns jsonb language plpgsql security definer set search_path=public as $$
declare j jsonb;
begin
 if not public.sg_is_admin() then raise exception 'Akses admin ditolak'; end if;
 select coalesce(jsonb_agg(jsonb_build_object(
   'affiliate_email',a.email,'referral_code',a.referral_code,
   'total_referrals',(select count(*) from public.sg_referrals_v6 r where r.affiliate_email=a.email),
   'total_transactions',(select count(*) from public.sg_commissions_v6 c where c.affiliate_email=a.email),
   'total_commission',(select coalesce(sum(c.commission_amount),0) from public.sg_commissions_v6 c where c.affiliate_email=a.email),
   'paid_commission',(select coalesce(sum(w.amount),0) from public.sg_withdrawals_v6 w where w.affiliate_email=a.email and w.status='Dibayar')
 ) order by a.created_at desc),'[]'::jsonb) into j from public.sg_affiliates_v6 a where a.active=true;
 return j;
end $$;

-- Product admin delete (fitur tombol Hapus).
create or replace function public.sg_admin_catalog_delete_v6(p_id uuid)
returns boolean language plpgsql security definer set search_path=public as $$
begin
 if not public.sg_is_admin() then raise exception 'Akses admin ditolak'; end if;
 delete from public.sg_catalog_products where id=p_id;
 return found;
end $$;

-- Execute permissions hanya melalui RPC yang sesuai.
grant execute on function public.sg_affiliate_sync_self_v6() to authenticated;
grant execute on function public.sg_affiliate_attach_referral_v6(text) to authenticated;
grant execute on function public.sg_create_order_v6(text,text,bigint,text,text,text) to authenticated;
grant execute on function public.sg_check_order_v6(text) to authenticated;
grant execute on function public.sg_submit_payment_v6(text,text) to authenticated;
grant execute on function public.sg_admin_list_orders_v6() to authenticated;
grant execute on function public.sg_admin_set_status_v6(text,text) to authenticated;
grant execute on function public.sg_admin_deliver_access_v6(text,text,text,text) to authenticated;
grant execute on function public.sg_affiliate_eligibility_v6() to authenticated;
grant execute on function public.sg_affiliate_me_v6() to authenticated;
grant execute on function public.sg_affiliate_commissions_v6() to authenticated;
grant execute on function public.sg_request_withdraw_v6(bigint,text,text,text) to authenticated;
grant execute on function public.sg_my_withdrawals_v6() to authenticated;
grant execute on function public.sg_admin_list_withdrawals_v6() to authenticated;
grant execute on function public.sg_admin_finish_withdraw_v6(bigint,boolean,text,text) to authenticated;
grant execute on function public.sg_admin_affiliate_summary_v6() to authenticated;
grant execute on function public.sg_admin_catalog_delete_v6(uuid) to authenticated;

notify pgrst,'reload schema';
commit;
